### ISSUE TITLE
[ 3 ] Auto Weapon Detection  ( check comments for in-depth info )

### ISSUE THREAD

**Issue by maciok12345** [lukaswozniak/ikigami#15]
( all templates we need are stored for sure )
( multi monitors support )
 ( all resolutions supported including custom ones with or without black bars ) 
 ( gpu scanning  instead of cpu   preferably ) ( no freezes )
 ( accurate scanning time  for 1/2/3/4/5/6 and // optional mouse-scroll aswell )

**Comment by maciok12345** [comment]
po prostu to ma smigac 🗡️

**Comment by lukaswozniak** [comment]
Kolory ekwipunku z gry:

public static Color defaultBackgroundColor = new Color(0.96862745f, 0.92156863f, 0.88235295f, 0.03529412f);
public static Color selectedBackgroundColor = new Color(0.12156863f, 0.41960785f, 0.627451f, 0.78431374f);
